CI: ...

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -161,12 +161,7 @@ cluster:
       - EXIT_CODE=0
       - cmake --build build -- check || EXIT_CODE=$?
       - ldd build/libOTFCPT.so
-      - ldd_out=$(ldd build/libOTFCPT.so | grep -q "libstdc++")
-      - |
-        if [[ "{ldd_out}" == "0" ]]; then
-          echo "Error: libOTFCPT.so is linked against libstdc++"
-          EXIT_CODE=1
-        fi
+      - ldd build/libOTFCPT.so | grep -q 'libcstd++' && echo "Error: libstdc++ linked" && EXIT_CODE=1 || echo "Info: No libstdc++ dependency found"
       - exit $EXIT_CODE
     artifacts:
       reports:
