Allow building OTF-CPT with GNU compiler (#22)
* uses omp-tools.h from external directory
* for OpenMP analysis of applications, the application must still be linked with libomp (LLVM/Intel runtime)
* adds CI pipelines for testing GCC

---------

Co-authored-by: felix.tomski <tomski@itc.rwth-aachen.de>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -29,6 +29,7 @@ stages:
   parallel:
     matrix:
        - MPI: [ mpich, openmpi ]
+         USE_CLANG: ["0", "1"]
   needs: []
   variables:
     CMAKE_BUILD_TYPE: Debug
@@ -36,6 +37,7 @@ stages:
     OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"
     OMPI_MCA_mpi_yield_when_idle: "1"
     OMPI_MCA_rmaps_base_oversubscribe: "1"
+    FF_SCRIPT_SECTIONS: "1"
   before_script:
     - export DEBIAN_FRONTEND=noninteractive
     - apt-get update
@@ -51,13 +53,19 @@ stages:
       git
       python3
       libxml2-dev
-      clang
       libomp-dev
       llvm-14-tools
   script:
+    - |
+      if [[ "${USE_CLANG}" == "1" ]]; then
+        apt-get install -y --no-install-recommends clang
+        export MPICH_CC=clang MPICH_CXX=clang++
+        export OMPI_CC=clang OMPI_CXX=clang++
+      else
+        export MPICH_CC=gcc MPICH_CXX=g++
+        export OMPI_CC=gcc OMPI_CXX=g++
+      fi
     - export PATH=$PATH:/usr/lib/llvm-14/bin
-    - export MPICH_CC=clang MPICH_CXX=clang++
-    - export OMPI_CC=clang OMPI_CXX=clang++
     - export FI_PROVIDER=shm MPIR_CVAR_POLLS_BEFORE_YIELD=1
     - export OMPI_MCA_btl=vader,self OMPI_MCA_mpi_yield_when_idle=1
     - >-
@@ -68,10 +76,10 @@ stages:
                            -DOTFCPT_TEST_UB=1.05 \
                            -DOTFCPT_TEST_WORK=300000
     - cmake --build build
-    - ldd build/libOTFCPT.so | grep -q "libstdc++" && echo -e "\e[1;31mFound libstdc++ dependency, failure\e[0m" && exit 1
     - cmake --install build
     - EXIT_CODE=0
     - cmake --build build -- check || EXIT_CODE=$?
+    - ldd build/libOTFCPT.so | grep -q "libstdc++" && echo -e "\e[1;31mFound libstdc++ dependency, failure\e[0m" && exit 1
     - exit $EXIT_CODE
   artifacts:
     reports:
@@ -94,13 +102,14 @@ debian:
 
 .cluster-template:
     tags: 
-      - "unstable"
+      - "downscope-testing"
     variables:
-      SLURM_CPUS_PER_TASK: "4"
-      SRUN_CPUS_PER_TASK: "4"
-      SLURM_ACCOUNT: "rwth1282" 
-      SLURM_PARTITION: "c23ms" 
-      SLURM_TIME: "15" 
+      SLURM_PARAM_CPUS_PER_TASK: "-c 4"
+      SLURM_PARAM_ACCOUNT: "-A rwth1282"
+      SLURM_PARAM_PARTITION: "-p c23ms"
+      SLURM_DPARAM_ACCOUNT: "-A rwth1282"
+      SLURM_DPARAM_PARTITION: "-p c23ms"
+      CI_MODE: "Srun"
     before_script:
       - module purge
       - module load "${TOOLCHAIN}/${VERSION}"
@@ -121,32 +130,42 @@ debian:
     parallel:
       matrix:
         - TOOLCHAIN: ["iimpi"]
-          VERSION: ["2022a", "2022b", "2023a", "2023b", "2024a"]
+          VERSION: ["2022a", "2022b", "2023a", "2023b"]
           COMPILER: [""]
           USE_ONEAPI: ["0", "1"]
         - TOOLCHAIN: ["iimpi"]
-          VERSION: ["2020b", "2021b", "2022a", "2022b", "2023a", "2023b"]
+          VERSION: ["2024a"] # These versions do not include the legacy compilers
+          COMPILER: [""]
+          USE_ONEAPI: ["1"]
+        - TOOLCHAIN: ["iimpi"]
+          VERSION: ["2022a", "2023a", "2023b", "2024a"]
           COMPILER: ["Clang"]
         - TOOLCHAIN: ["gompi"]
-          VERSION: ["2020b", "2021b", "2022a", "2022b", "2023a", "2023b"]
-          COMPILER: ["Clang"]
+          VERSION: ["2022a", "2023a", "2023b", "2024a"]
+          COMPILER: ["Clang", ""]
+        - TOOLCHAIN: ["iimpi", "gompi"]
+          VERSION: ["2025a"]
+          COMPILER: ["LLVM", ""]
 
-cluster-build:
+.cluster-build:
     stage: build
     extends: .cluster-template
     script:
       - mkdir build
       - cmake -S ./ -B build -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_BUILD_TYPE=RelWithDebInfo
-      - cmake --build build
-      - ldd build/libOTFCPT.so | grep -q "libstdc++" && echo -e "\e[1;31mFound libstdc++ dependency, failure\e[0m" && exit 1
+      - cmake --build build --parallel ${SLURM_CPUS_PER_TASK} -v
       - cmake --install build
 
 cluster:
     stage: test
     extends: .cluster-template
     script:
-      - !reference [cluster-build, script]
-      - cmake --build build -- check
+      - !reference [.cluster-build, script]
+      - EXIT_CODE=0
+      - cmake --build build -- check || EXIT_CODE=$?
+      - ldd build/libOTFCPT.so
+      - ldd build/libOTFCPT.so | grep -q 'libstdc++' && echo "Error libstdc++ linked" && exit 1 || echo "Info No libstdc++ dependency found"
+      - exit $EXIT_CODE
     artifacts:
       reports:
         junit: build/tests/check.xunit.xml
